version: '3.8'

services:
  web:
    build: .
    ports:
      - "6546:6546"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - .:/app
    restart: unless-stopped
