name: EC2 Infrastructure
permissions:
  contents: read
  id-token: write
on:
  push:
    branches:
      - main
    paths:
      - terraform/**
      - .github/workflows/infrastructure.yml
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'Production'
        type: choice
        options:
          - Test
          - Production

env:
  TERRAFORM_WORKING_DIR: './terraform'

jobs:
  Plan:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'Production' }}

    steps:
      - name:  Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ vars.region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.3"

      - name: Format Terraform
        id: fmt
        run: |
          terraform fmt -check -recursive
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}

      - name: Initialize Terraform
        id: init
        run: |
          terraform init
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
        env:
          TF_LOG: INFO

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -var="github_repo=${{ github.server_url }}/${{ github.repository }}.git"
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}

